### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by 029onikyu** [HoneybunchBuilder/toybox#10]
Thank you so much for your hard work on vcpkg ports for Steam Audio and SDL3. I was able to finally get these dependencies building because of the work you did on them. Sending some appreciation your way!

**Comment by Honeybunch** [comment]
This made my morning. Thank you very much 😊

**Comment by Honeybunch** [comment]
SDL3 pre-release port should be merged upstream soon 😄 https://github.com/microsoft/vcpkg/pull/40867
